### ISSUE TITLE
statistics KO OK not updated after scripts change/save

### ISSUE THREAD

**Issue by guillaume-chervet** [AxaGuilDEv/ml-cli#50]
the screenshot bellow come from Meetup.

You updated the script :

for the filed firstname the Number OK shoub be 4 and not 5.

![image](https://user-images.githubusercontent.com/52236059/127661717-b46fc821-3040-4bd3-9ca7-5db5e7d04769.png)

**Comment by lilian-delouvy** [comment]
Le screenshot indique que la clé lastname a 4 OK pour 1 KO. Si je me souviens bien, c'est la clé lastname que j'ai modifiée, pas la clé firstname. Dans ce cas, les statistiques KO/OK sont bonnes !
